### ISSUE TITLE
App crashes automatically after selecting video

### ISSUE THREAD

**Issue by kuldeepworkid** [Shobbak/react-native-compressor#23]
**The crash is happening when we select compressionMethod: 'manual'**
await Video.compress(
        imgData.path,
        {
          compressionMethod: 'manual',
          maxSize: imgData.height,
          bitrate: 450000,
        },
        progress => {
          console.log('prog===>', progress);
        },
      );
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:466)
        at com.zolad.videoslimmer.VideoSlimEncoder.releaseCoder(VideoSlimEncoder.java:622)
        at com.zolad.videoslimmer.VideoSlimEncoder.convertVideo(VideoSlimEncoder.java:391)
        at com.zolad.videoslimmer.VideoSlimTask.doInBackground(VideoSlimTask.java:30)
        at com.zolad.videoslimmer.VideoSlimTask.doInBackground(VideoSlimTask.java:11)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2021-07-27 18:51:03.330 25348-25644/com.dt.thanthiwhistle E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3

**Comment by nomi9995** [comment]
@kuldeepworkid can you send me a video so I can reproduce it on my side

**Comment by kuldeepworkid** [comment]
> @kuldeepworkid can you send me a video so I can reproduce it on my side

https://drive.google.com/file/d/1jw5XqDf9pMWJrSMwwTWrR-Bbx1tafFxl/view?usp=sharing

**Comment by nomi9995** [comment]
Closing due to inactivity.
