### ISSUE TITLE
While compressing the video file in Android returning Empty Value 

### ISSUE THREAD

**Issue by asadraza4522** [Shobbak/react-native-compressor#95]
While trying to compress the video file in the Android after updating to the new version 1.5.1 before that it is working but in IOS working Fine. Also Not show this Progress console :

import {
  Image as ImageCompress,
  Video as VideoCompress,
  getRealPath,
} from 'react-native-compressor';

let uri = file:///storage/emulated/0/Download/zapya/video/VID-20201103-WA0022.mp4 

const videoResult = await VideoCompress.compress(
      uri,
      {
        compressionMethod: 'auto',
      },
      progress => {
        console.log('Video Compression Progress: ', progress);
      },
    );

console.log(
      'Video Compress : ',  videoResult 
 );

**output :** Video Compress :

**Comment by nomi9995** [comment]
@asadraza4522 can you put `try-catch` around this code and tell me the actual error so i can investigate.

**Comment by asadraza4522** [comment]
> @asadraza4522 can you put `try-catch` around this code and tell me the actual error so i can investigate.

Okay

**Comment by asadraza4522** [comment]
It is not throughing any error

**Comment by nomi9995** [comment]
@asadraza4522 can you see the `Logcat` of android. you will get an exception in `Logcat`. can you post that exception here?

**Comment by asadraza4522** [comment]
2022-02-15 10:59:21.998 423-689/com.pokApp I/ReactNativeJS: 'Route Params in the Media Page: ', { path: 'file:///data/user/0/com.pokApp/cache/VisionCamera-20220215_1059033322254063905032255.mp4',
      type: 'video',
      postTypeValue: 'Move' }
2022-02-15 10:59:22.007 423-423/com.pokApp I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
2022-02-15 10:59:22.062 423-423/com.pokApp I/HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
2022-02-15 10:59:27.548 423-691/com.pokApp V/AudioManager: playSoundEffect   effectType: 0
2022-02-15 10:59:27.548 423-691/com.pokApp V/AudioManager: querySoundEffectsEnabled...
2022-02-15 10:59:28.438 423-438/com.pokApp I/com.pokApp: Background concurrent copying GC freed 276876(12MB) AllocSpace objects, 0(0B) LOS objects, 53% free, 10MB/22MB, paused 223us total 114.256ms
2022-02-15 10:59:28.444 423-436/com.pokApp W/System: A resource failed to call release. 
2022-02-15 10:59:29.598 423-423/com.pokApp I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
2022-02-15 10:59:29.662 423-689/com.pokApp I/ReactNativeJS: Compress videos: 
2022-02-15 10:59:29.663 423-689/com.pokApp I/ReactNativeJS: 'Video Compress file path: ', 'file:///data/user/0/com.pokApp/cache/VisionCamera-20220215_1059033322254063905032255.mp4'
2022-02-15 10:59:29.664 423-691/com.pokApp V/AudioManager: playSoundEffect   effectType: 0
2022-02-15 10:59:29.664 423-691/com.pokApp V/AudioManager: querySoundEffectsEnabled...
2022-02-15 10:59:29.677 423-689/com.pokApp I/ReactNativeJS: 'Route Params in the Media Page: ', { path: 'file:///data/user/0/com.pokApp/cache/VisionCamera-20220215_1059033322254063905032255.mp4',
      type: 'video',
     }
2022-02-15 10:59:29.768 423-423/com.pokApp I/HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
2022-02-15 10:59:29.782 423-689/com.pokApp I/ReactNativeJS: 'Video Compress : ', ''
2022-02-15 10:59:29.783 423-689/com.pokApp I/ReactNativeJS: 'uri : ', ''
2022-02-15 10:59:29.802 423-689/com.pokApp I/ReactNativeJS: 'File Name : ', ''
2022-02-15 10:59:29.920 423-423/com.pokApp I/HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
2022-02-15 10:59:30.893 423-423/com.pokApp I/HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
2022-02-15 10:59:30.894 423-689/com.pokApp I/ReactNativeJS: 'Route Params in the Media Page: ', { path: 'file:///data/user/0/com.pokApp/cache/VisionCamera-20220215_1059033322254063905032255.mp4',
      type: 'video',
      }
2022-02-15 10:59:30.970 423-689/com.pokApp I/ReactNativeJS: 'Photo : ', ' body : video/undefined'
2022-02-15 10:59:30.970 423-689/com.pokApp I/ReactNativeJS: 'POst Token  : ', 'U2FsdGVkX1+lb3Gw5XJ50HCqUkZE65TUx91hQSqk2Ay6DPxVK0pPhL2NqVcK5uEEisVideo 1'
2022-02-15 10:59:30.971 423-689/com.pokApp I/ReactNativeJS: 'Upload Request : ', '{\n  "_parts": [\n    [\n      "Token",\n      "U2FsdGVkX1+lb3Gw5XJ50HCqUkZE65TUx91hQSqk2Ay6DPxVK0pPhL2NqVcK5uEE"\n    ],\n    [\n      "video",\n      1\n    ],\n    [\n      "file",\n      {\n        "name": "",\n        "type": "video/undefined",\n        "uri": ""\n      }\n    ]\n  ]\n}'
2022-02-15 10:59:30.984 423-691/com.pokApp E/unknown:ReactNative: Could not retrieve file for contentUri 
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
        at com.facebook.react.modules.network.RequestBodyUtil.getFileInputStream(RequestBodyUtil.java:58)
        at com.facebook.react.modules.network.NetworkingModule.constructMultipartBody(NetworkingModule.java:715)
        at com.facebook.react.modules.network.NetworkingModule.sendRequestInternal(NetworkingModule.java:437)
        at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:243)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:216)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:784)
2022-02-15 10:59:30.987 423-423/com.pokApp I/HwPhoneWindow: updateLayoutParamsColor false mSpecialSet=false, mForcedNavigationBarColor=false, navigationBarColor=ff000000, mNavBarShow=false, mIsFloating=false
2022-02-15 10:59:31.007 423-689/com.pokApp I/ReactNativeJS: 'error', '{"line":27694,"column":33,"sourceURL":"http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.pokApp&modulesOnly=false&runModule=true"}'
2022-02-15 10:59:31.028 423-689/com.pokApp I/ReactNativeJS: 'Route Params in the Media Page: ', { path: 'file:///data/user/0/com.pokApp/cache/VisionCamera-20220215_1059033322254063905032255.mp4',
      type: 'video',
      }

**Comment by nomi9995** [comment]
@asadraza4522 I have checked on my local, it is working on my side. can you connect with me on LinkedIn https://numan.dev , i wanna see it on zoom in free time

**Comment by ijhar8** [comment]
@nomi9995  how did you fixed it ?
